development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: hifibuys_development
  pool: 5
  username: postgres
  password: postgres 
  host: localhost

test: &TEST
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: hifibuys_test
  username: postgres
  password: postgres 
  host: localhost
  #adapter: nulldb
#  adapter: sqlite3
#  database: db/test.sqlite3
#  pool: 5


production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: hifibuys_production
  pool: 5
  username: postgres
  password: postgres 
  host: localhost

cucumber:
  <<: *TEST
