development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: hifibuys_development
  pool: 5
  username: postgres
  password: postgres 
  host: localhost

test: &TEST
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: hifibuys_test
  pool: 5
  username: postgres
  password: postgres 
  host: localhost


production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: hifibuys_production
  pool: 5
  username: postgres
  password: postgres 
  host: localhost

cucumber:
  <<: *TEST
