base: &BASE
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres

development:
  database: hifibuys_development
  <<: *BASE

test: &TEST
  adapter: nulldb

production:
  <<: *BASE
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
