--- 
- :name: hpricot
- :version: ~> 2.3.11
  :name: will_paginate
  :source: http://gemcutter.org
- :name: brianmario-yajl-ruby
  :source: http://gems.github.com
- :name: rubaidh-google_analytics
  :source: http://gems.github.com
- :name: oauth
- :name: hashie
- :version: = 0.0.3
  :name: mash
- :version: = 0.4.3
  :name: httparty
- :name: jnunemaker-twitter
  :source: http://gems.github.com
- :name: builder
- :name: mysql
- :name: acts-as-taggable-on
  :source: http://gemcutter.org
- :version: = 1.3.11
  :name: thinking-sphinx
- :version: ">= 2.0.4"
  :name: ruby-openid
- :version: 2.3.4
  :name: rails
