--- 
- :name: mislav-will_paginate
  :source: http://gems.github.com
- :name: brianmario-yajl-ruby
  :source: http://gems.github.com
- :name: rubaidh-google_analytics
  :source: http://gems.github.com
- :name: mysql
- :version: 2.3.4
  :name: rails
