development:
  audio_connection:
    ingestor: audio_connection
    params:
      url: test/siteref/audioconnection.html
      notify: none
      container:
        object: Item
        defaults:
          group: audio_connection
  tivoli:
    ingestor: tivoli
    params:
      url: 
      - test/siteref/tivoli.html
      - test/siteref/tivoli2.html
      notify: none
      container:
        object: Item
        defaults:
          group: tivoli
  pymble:
    ingestor: pymble
    params:
      url: test/siteref/pymble.html
      notify: none
      container:
        object: Item
        notify: none
        defaults:
          group: pymble
  carlton:
    ingestor: carlton
    params:
      url: test/siteref/carlton.html
      notify: none
      container:
        object: Item
        defaults:
          group: carlton
  caxton:
    ingestor: yql_opendatatable
    params:
      url: http://www.hifibuys.com.au/opendatatables/caxton-audio-yql.xml
      notify: none
      container:
        object: Item
        defaults:
          group: caxton
  ug_item:
    ingestor: ug_item
    params:
      url: http://blah.com
      notify: none
      container:
        object: Item
        defaults:
          group: ug_item

production:
  audio_connection:
    ingestor: audio_connection
    params:
      url: http://audioconnection.com.au/trade-ins-clearance-audio-equipment.asp
      notify: twitter
      container:
        object: Item
        defaults:
          group: audio_connection
  tivoli:
    ingestor: tivoli
    params:
      url:
      - http://tivolihifi.com/store/second-hand-equipment
      - http://tivolihifi.com/store/second-hand-equipment?q=second-hand-equipment&sort=20a&page=2
      notify: twitter
      container:
        object: Item
        defaults:
          group: tivoli
  carlton:
    ingestor: carlton
    params:
      url: http://www.carltonaudiovisual.com.au/?q=node/view/7
      notify: twitter
      container:
        object: Item
        defaults:
          group: carlton
  ug_item:
    ingestor: ug_item
    params:
      url: http://blah.com
      notify: none
      container:
        object: Item
        defaults:
          group: ug_item


