development:
  caxton:
    url: http://www.hifibuys.com.au/opendatatables/caxton-audio-yql.xml
    ingestor: yql_opendatatable
  hifijunction:
    url: http://www.hifibuys.com.au/opendatatables/hifijunction-yql.xml
    ingestor: yql_opendatatable
  audio_connection:
    ingestor: audio_connection
    params:
      url: /home/robsharp/Dropbox/workspace/hifibuys/test/siteref/audioconnection.html
      container:
        object: Item
        defaults:
          shop_name: Audio Connection
          shop_address: 
          shop_suburb: Leichhardt
          shop_city: Sydney
          shop_state: NSW
          shop_country: Australia
  tivoli:
    ingestor: tivoli
    params:
      url: /home/robsharp/Dropbox/workspace/hifibuys/test/siteref/tivoli.html
      container:
        object: Item
        defaults:
          shop_name: Tivoli
          shop_address: 155-157 Camberwell Road
          shop_suburb: Hawthorn East
          shop_city: Melbourne
          shop_state: VIC
          shop_country: Australia
  pymble:
    ingestor: pymble
    params:
      url: /home/robsharp/Dropbox/workspace/hifibuys/test/siteref/pymble.html
      container:
        object: Item
        defaults:
          shop_name: Pymble HiFi
          shop_address: 
          shop_suburb: Suburb
          shop_city: City
          shop_state: State
          shop_country: Australia  
  carlton:
    ingestor: carlton
    params:
      url: /home/robsharp/Dropbox/workspace/hifibuys/test/siteref/carlton.html
      container:
        object: Item
        defaults:
          shop_name: Carlton HiFi
          shop_address: 
          shop_suburb: Suburb
          shop_city: City
          shop_state: State
          shop_country: Australia  

production:
  audio_connection:
    ingestor: audio_connection
    params:
      url: http://audioconnection.com.au/trade-ins-clearance-audio-equipment
      container:
        object: Item
        defaults:
          shop_name: Audio Connection
          shop_address: 
          shop_suburb: Leichhardt
          shop_city: Sydney
          shop_state: NSW
          shop_country: Australia
  tivoli:
    ingestor: tivoli
    params:
      url:
      - http://tivolihifi.com/second-hand-equipment
      - http://tivolihifi.com/second-hand-equipment?&sort=20a&page=2
      container:
        object: Item
        defaults:
          shop_name: Tivoli
          shop_address: 155-157 Camberwell Road
          shop_suburb: Hawthorn East
          shop_city: Melbourne
          shop_state: VIC
          shop_country: Australia
  carlton:
    ingestor: carlton
    params:
      url: http://www.carltonaudiovisual.com.au/?q=node/view/7
      container:
        object: Item
        defaults:
          shop_name: Carlton HiFi
          shop_address: 164-172 Lygon St
          shop_suburb: Carlton
          shop_city: Melbourne
          shop_state: Victoria
          shop_country: Australia  
