development:
  caxton:
    url: http://www.hifibuys.com.au/opendatatables/caxton-audio-yql.xml
    ingestor: yql_opendatatable
  hifijunction:
    url: http://www.hifibuys.com.au/opendatatables/hifijunction-yql.xml
    ingestor: yql_opendatatable
  audio_connection:
    ingestor: audio_connection
    params:
      url: /home/robsharp/Dropbox/workspace/hifibuys/test/siteref/audioconnection.html
      container:
        object: Item
        defaults:
          shop_name: Audio Connection
          shop_address: 
          shop_suburb: Leichardt
          shop_state: NSW
          shop_country: Australia
production:
  audio_connection:
    ingestor: audio_connection
    params:
      url: http://audioconnection.com.au/trade-ins-clearance-audio-equipment
      container:
        object: Item
        defaults:
          shop_name: Audio Connection
          shop_address: 
          shop_suburb: Leichardt
          shop_state: NSW
          shop_country: Australia

