# Configuration options for your blog - customise to taste
# This file contains no secret information, so can be stored in source control (unlike database.yml)
title: HifiBuys
url:   http://www.hifibuyse.com.au
author: 
  name:    Hifibuys        # For copyright notice and ATOM feeds
  email:   admin@hifibuys.com.au # Exception emails will go here, and it is used in ATOM feeds
  open_id:                  # These are used to login to the admin area
      - http://rob.sharp.id.au

# Delete the following section if your site will not be acting as an OpenID delegate (http://wiki.openid.net/Delegation)
# If you're deploying with mongrel, make sure you read http://rhnh.net/2008/04/13/nginx-openid-delegation-and-yadis
open_id_delegation:
  server:   https://open.login.yahooapis.com/openid/op/auth
  delegate: https://me.yahoo.com/r0bsharp
