shop_1:
  name: Tivoli
  city: Melbourne
  address: 155-157 Camberwell Road
  created_at: Sun Sep 12 21:40:39 UTC 2010
  country: Australia
  updated_at: Sun Sep 12 21:40:39 UTC 2010
  suburb: Hawthorn East
  id: 208
  ingestor: Tivoli
  state: VIC
  feed: spec/integration/siteref/tivoli.html
  #feed: http://tivolihifi.com/store/second-hand-equipment

shop_2:
  name: Carlton Audio Visual
  city: Melbourne
  address: 164-172 Lygon Street
  created_at: Sun Sep 12 21:40:39 UTC 2010
  country: Australia
  updated_at: Sun Sep 12 21:40:39 UTC 2010
  suburb: Carlton
  id: 209
  ingestor: Carlton
  state: Victoria
  feed: spec/integration/siteref/carlton.html
  #feed: http://www.carltonaudiovisual.com.au/?q=node/view/7

shop_3:
  name: Audio Connection
  city: Sydney
  address: 
  created_at: Sun Sep 12 21:40:40 UTC 2010
  country: Australia
  updated_at: Sun Sep 12 21:40:40 UTC 2010
  suburb: Leichhardt
  id: 210
  ingestor: AudioConnection
  state: NSW
  feed: spec/integration/siteref/audioconnection.html
  #feed: http://audioconnection.com.au/trade-ins-clearance-audio-equipment.asp
