--- 
- 
  name: Tivoli
  city: Melbourne
  address: 155-157 Camberwell Road
  country: Australia
  suburb: Hawthorn East
  state: VIC
  feed: http://tivolihifi.com/store/second-hand-equipment
  ingestor: TivoliIngestor

- 
  name: Carlton Audio Visual
  city: Melbourne
  address: 164-172 Lygon Street
  country: Australia
  suburb: Carlton
  state: Victoria
  feed: http://www.carltonaudiovisual.com.au/?q=node/view/7
  ingestor: CarltonIngestor
- 
  name: Audio Connection
  city: Sydney
  address: ""
  country: Australia
  suburb: Leichhardt
  state: NSW
  feed: http://audioconnection.com.au/trade-ins-clearance-audio-equipment.asp
  ingestor: AudioConnectionIngestor
