development:
  ingestor: carlton
  params:
    url: test/siteref/carlton.html
    notify: none
    container:
      object: Item
      defaults:
        group: carlton
production:
  ingestor: carlton
  params:
    url: http://www.carltonaudiovisual.com.au/?q=node/view/7
    notify: twitter
    container:
      object: Item
      defaults:
        group: carlton
