development:
  ingestor: tivoli
  params:
    url: 
    - test/siteref/tivoli.html
    - test/siteref/tivoli2.html
    notify: none
    container:
      object: Item
      defaults:
        group: tivoli
production:
  ingestor: tivoli
  params:
    url:
    - http://tivolihifi.com/store/second-hand-equipment
    - http://tivolihifi.com/store/second-hand-equipment?q=second-hand-equipment&sort=20a&page=2
    notify: twitter
    container:
      object: Item
      defaults:
        group: tivoli
